// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmzBmCpqxu0THHB6K7yUBXpcRh3-TE_PE',
    appId: '1:581928598897:web:e09ad58f41be261bcf0ad0',
    messagingSenderId: '581928598897',
    projectId: 'fwpj-56591',
    authDomain: 'fwpj-56591.firebaseapp.com',
    storageBucket: 'fwpj-56591.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJykuEGUNtRhOSWpz4xlBGRpsyM-wjb4',
    appId: '1:581928598897:android:8c871a0febe5a2adcf0ad0',
    messagingSenderId: '581928598897',
    projectId: 'fwpj-56591',
    storageBucket: 'fwpj-56591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9mt03BD8SqU2fh70RzFE-gxrB4DymnI',
    appId: '1:581928598897:ios:6954d7936bece7becf0ad0',
    messagingSenderId: '581928598897',
    projectId: 'fwpj-56591',
    storageBucket: 'fwpj-56591.appspot.com',
    iosBundleId: 'com.example.fw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmzBmCpqxu0THHB6K7yUBXpcRh3-TE_PE',
    appId: '1:581928598897:web:2d38413ff88e13b1cf0ad0',
    messagingSenderId: '581928598897',
    projectId: 'fwpj-56591',
    authDomain: 'fwpj-56591.firebaseapp.com',
    storageBucket: 'fwpj-56591.appspot.com',
  );
}
